# ================================
#       BUILDER STAGE
# ================================
FROM python:3.11-alpine AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    TZ=America/Sao_Paulo \
    LANG=C.UTF-8

RUN apk add --no-cache --update \
    build-base \
    libffi-dev \
    musl-dev \
    postgresql-dev \
    bash \
    tzdata \
    graphviz-dev

WORKDIR /app

COPY requirements.txt .
RUN pip install --prefix=/install -r requirements.txt


# ================================
#       FINAL STAGE
# ================================
FROM python:3.11-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TZ=America/Sao_Paulo \
    LANG=C.UTF-8

RUN apk add --no-cache \
    libffi \
    postgresql-libs \
    bash \
    tzdata

WORKDIR /app

COPY --from=builder /install /usr/local
COPY . /app

RUN python manage.py collectstatic --noinput

RUN adduser -D django
USER django

EXPOSE 8000

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
