# Generated by Django 4.2.22 on 2025-10-28 00:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_code', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('fantasy_name', models.CharField(max_length=255)),
                ('social_reason', models.CharField(max_length=255)),
                ('opening_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('cnae', models.CharField(max_length=255)),
                ('type_of', models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier')], max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='backend.address')),
            ],
        ),
    ]
