# Generated by Django 4.2.22 on 2025-11-10 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paid_at', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('debit', 'Debit'), ('credit', 'Credit'), ('pix', 'Pix')], max_length=15)),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.billingaccount')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.title')),
            ],
            options={
                'ordering': ['-paid_at', 'uuid'],
                'indexes': [models.Index(fields=['title', 'paid_at'], name='backend_ent_title_i_cab582_idx')],
            },
        ),
    ]
