# Generated by Django 4.2.22 on 2025-10-11 05:41

import backend.domain.company.company_value_objects
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('accountant', 'Contador'), ('manager', 'Gestor'), ('staff', 'Colaborador')], default='client', max_length=20, verbose_name='Papel no sistema'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[backend.domain.company.company_value_objects.validate_cnpj], verbose_name='CNPJ')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo da Empresa')),
                ('state_registration', models.CharField(blank=True, max_length=30, null=True, validators=[backend.domain.company.company_value_objects.validate_ie], verbose_name='Inscrição Estadual (IE)')),
                ('municipal_registration', models.CharField(blank=True, max_length=30, null=True, validators=[backend.domain.company.company_value_objects.validate_im], verbose_name='Inscrição Municipal (IM)')),
                ('cnae_main', models.CharField(blank=True, help_text='Formato NNNN-N/NN', max_length=10, null=True, validators=[backend.domain.company.company_value_objects.validate_cnae], verbose_name='CNAE Principal')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, validators=[backend.domain.company.company_value_objects.validate_cep], verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='Estado (UF)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[backend.domain.company.company_value_objects.validate_phone], verbose_name='Telefone Fixo')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[backend.domain.company.company_value_objects.validate_phone], verbose_name='Telefone Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Principal')),
                ('tax_regime', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20, verbose_name='Regime Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['cnpj'], name='idx_company_cnpj')],
            },
        ),
    ]
