# Generated by Django 4.2.22 on 2025-11-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
