# Generated by Django 4.2.22 on 2025-10-29 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_billingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('analytic', 'Analítica'), ('synthetic', 'Sintética')], editable=False, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('classification', models.PositiveSmallIntegerField(editable=False)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_accounts', to='backend.billingplan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='backend.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.billingaccount')),
            ],
        ),
    ]
