# Generated by Django 4.2.22 on 2025-11-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.preset'),
        ),
        migrations.AlterField(
            model_name='title',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
    ]
