# Generated by Django 4.2.22 on 2025-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_preset_active_title_preset_alter_title_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='payable_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preset',
            name='receivable_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
