# Generated by Django 4.2.22 on 2025-11-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_preset_payable_name_preset_receivable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='payable_name',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='receivable_name',
        ),
    ]
