# Generated by Django 4.2.22 on 2025-10-23 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_usercompany_user_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type_of', models.CharField(choices=[('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='backend.company')),
            ],
        ),
    ]
