# Generated by Django 4.2.22 on 2025-11-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_preset_payable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='payable_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preset',
            name='receivable_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
