# Generated by Django 4.2.22 on 2025-11-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_entry'),
        ('backend', '0005_preset_payable_name_preset_receivable_name'),
    ]

    operations = [
    ]
