# Generated by Django 4.2.22 on 2025-11-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaccount',
            name='classification',
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='billing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='backend.billingplan'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['billing_plan', 'parent'], name='backend_bil_billing_7dcf02_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['code'], name='backend_bil_code_f8ed02_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['account_type'], name='backend_bil_account_5105d1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingplan',
            index=models.Index(fields=['name'], name='backend_bil_name_a1b07e_idx'),
        ),
    ]
