# Generated by Django 4.2.22 on 2025-11-20 02:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_legacy_preset_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(choices=[('title_creation', 'Title Creation'), ('title_settlement', 'Title Settlement'), ('title_settlement_reverse', 'Title Settlement Reverse')], max_length=255)),
                ('reference_id', models.CharField(max_length=64)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='backend.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='backend.billingaccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.journalentry')),
            ],
            options={
                'indexes': [models.Index(fields=['journal'], name='backend_jou_journal_c0e5d3_idx'), models.Index(fields=['account'], name='backend_jou_account_66e521_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='backend_jou_referen_18639c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='backend_jou_date_158d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('reference_type', 'reference_id'), name='uniq_ref'),
        ),
    ]
