name: CD

on:
  workflow_run:
    workflows: ['CI']
    branches: [main, dev]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: EC2_HOST
    permissions:
      contents: read
      actions: read
      packages: read

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            BRANCH="${{ github.event.workflow_run.head_branch }}"
            REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "$REPO_OWNER" --password-stdin

            if [ "$BRANCH" = "main" ]; then
              TAG="prod"
            else
              TAG="dev"
            fi

            BACK_IMAGE="ghcr.io/$REPO_OWNER/backend:$TAG"
            FRONT_IMAGE="ghcr.io/$REPO_OWNER/frontend:$TAG"

            echo "Pulling images..."
            docker pull "$BACK_IMAGE"
            docker pull "$FRONT_IMAGE"

            echo "Stopping old containers if exist..."
            docker rm -f backend || true
            docker rm -f frontend || true

            echo "Starting backend..."
            docker run -d \
              --name backend \
              --restart always \
              -p 8000:8000 \
              -e DJANGO_SETTINGS_MODULE=config.settings.django \
              "$BACK_IMAGE"

            sleep 5

            echo "Running Django migrations..."
            docker exec backend python manage.py migrate --noinput

            echo "Starting frontend..."
            docker run -d \
              --name frontend \
              --restart always \
              -p 3000:3000 \
              -e NEXT_TELEMETRY_DISABLED=1 \
              -e NEXT_PUBLIC_API_URL="http://localhost:8000/api/v1/" \
              "$FRONT_IMAGE"

            echo "Cleaning up unused images..."
            docker image prune -af
